---
title: " Commerical Salmon Fishing in Alaska"
author: "Kate Becker"
date: "2024-03-14"
output: html_document
---


## How Salmon Fisheries in Alaska Have Changed Since 1985

```{r}

```


### Downloading necessary packages and libraries 
```{r}
library(tidyverse)
library(streamgraph)
library(viridis)
library(hrbrthemes)
library(plotly)
library(ggalt)
library(jpeg) 
library(ggplot2) 
library(patchwork) 
library(dplyr)
library(ggimage)
library(ggpubr)
library(jpeg)
library(stringr)
library(prismatic)
library(Cairo)
library(scales)
library(extrafont)
library(hrbrthemes)
library(GGally)
library(viridis)
library(sf)
library(terra)
library(dplyr)
library(spData)
library(tibble)
library(fmsb)
library(ggh4x)
library(urbnmapr)
library(showtext)
library(ggrepel)
library(ggridges)
```


## Data read in
```{r}
alaska_state <- read_csv("data/Alaska-Statewide.csv")

alaska <- alaska_state %>%   
  janitor::clean_names()

```



```{r}

alaska$area <- as.factor(alaska$area)

summary_stats <- alaska %>%
  filter(year == "2023") %>%
  group_by(area) %>%
  summarise(mean_fish = mean(number_of_fish_estimated),
            sum_fish = sum(number_of_fish_estimated)) %>%
  mutate(mean_fish= round(mean_fish, digits = 0))

Nrs <- alaska %>%
  group_by(area) %>%
  count()

summary_all <- left_join(summary_stats, Nrs, by = "area")



# for grid below after ggpllot(summary_all)

    #make custom panel grid
  #geom_hline(yintercept = 0, color = "lightgrey") +
  #geom_hline(yintercept = 2000000, color = "lightgrey") +
  #geom_hline(yintercept = 4000000, color = "lightgrey") +
  #geom_hline(yintercept = 6000000, color = "lightgrey") +
  #geom_hline(yintercept = 80000000, color = "lightgrey") +
```


# DONE

```{r}
#color choice
prismatic::color(c( "#6C5B7B" ,"#C06C84","#B85265", "#F67280", "#FF7799", "#FF91A4","#FD7C6E", "#EC8E5E", "#FF7F50"))

#ggplot2

summary_all$area <- factor(summary_all$area, levels = sort(unique(summary_all$area)))


ggplot(summary_all) +

  
  geom_col(aes(
    #x = reorder(str_wrap(area,11),sum_fish), #is numeric
    x = area,
    y = sum_fish,#is numeric
    fill = sum_fish),
    show.legend = TRUE,
    ) +
      
      #new fill and legend title for number of tracks per region
  #scale_fill_gradientn("Salmon Catch Yields",
                      # colours = c("#B85265", "#F67280", "#FD7C6E", "#EC8E5E", "#FF7F50", "#FF7799", "#FF91A4"
  
  scale_fill_gradient(low = "#FFA07A", high = "#C66264", name = "Yearly Catch", labels = comma, breaks = c(0, 10000000, 20000000, 30000000, 40000000, 50000000, 60000000)) +                              #))

  scale_y_continuous(labels = scales::comma) +
  
  
  labs(y = "Estimated Catch") +
  
  guides (fill = guide_colourbar(direction = "vertical", barheight = 16)) +
  
  theme(axis.title.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.x = element_text(size=5, color = "black", face = "bold"), 
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y = element_blank(),
        plot.background = element_rect(fill = "lightblue"),
        panel.background = element_rect(fill = "lightblue"),
        panel.grid = element_line(color = "white"),
        legend.position = "right",
        legend.title = element_text(colour="black", size=8, 
                                      face="bold"),
        legend.text = element_text(angle = 45, hjust = 1, color = "black"),
        legend.background = element_rect(fill = "lightblue"),
        plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "lines"),
        plot.title = element_text(size = 18, hjust=1.3, vjust = -3.0, color = "black"),
        panel.spacing = unit(4, "lines")) +
  

  #theme(axis.title.x=element_blank(),
        #axis.ticks.x=element_blank(),
        #axis.text.y=element_blank(),
        #axis.title.y=element_blank(),
        #axis.ticks.y = element_blank(),
        #panel.background = element_rect(fill = "lightblue"),
        #panel.grid = element_line(color = "white"),
        #legend.position = "bottom",
        #legend.title = element_text(colour="black", size=8, 
                                      #face="bold")) +
          
  ggtitle("2023") +
  
  coord_polar()


```

## 1985 

# DONE

```{r}
alaska$area <- as.factor(alaska$area)

summary_stats_85 <- alaska %>%
  filter(year == "1985") %>%
  group_by(area) %>%
  summarise(mean_fish_85 = mean(number_of_fish_estimated),
            sum_fish_85 = sum(number_of_fish_estimated)) %>%
  mutate(mean_fish_85= round(mean_fish_85, digits = 0))

Nrs_85 <- alaska %>%
  group_by(area) %>%
  count()

summary_all_85 <- left_join(summary_stats_85, Nrs_85, by = "area")

#11 and 7 
summary_all_85 <- summary_all_85 %>%
  filter(!row_number() %in% c(7,11))
  


#color choice
prismatic::color(c( "#6C5B7B" ,"#C06C84","#B85265", "#F67280", "#FF7799", "#FF91A4","#FD7C6E", "#EC8E5E", "#FF7F50"))


summary_all_85$area <- factor(summary_all_85$area, levels = sort(unique(summary_all_85$area)))

#ggplot2
ggplot(summary_all_85) +

  
  geom_col(aes(
    #x = reorder(str_wrap(area,11),sum_fish_85), #is numeric
    x = area,
    y = sum_fish_85,#is numeric
    fill = sum_fish_85),
    show.legend = TRUE,
    stat = "identity"
    ) +
  
  scale_fill_gradient(low = "#FFA07A", high = "#C66264", name = "Yearly Catch", labels = comma, breaks = c(0, 10000000, 20000000, 30000000, 40000000, 50000000, 60000000)) + 
      
      #new fill and legend title for number of tracks per region
  #scale_fill_gradientn("Salmon Catch Yields",
                       #colours = c("#B85265", "#F67280", "#FD7C6E", "#EC8E5E", "#FF7F50", "#FF7799", "#FF91A4"
                                    #)) +
  
  labs(y = "Estimated Catch") +
  
  guides (fill = guide_colourbar(direction = "vertical", barheight = 16)) +
  

  theme(axis.title.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.x = element_text(size=5, color = "black", face = "bold"), 
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y = element_blank(),
        plot.background = element_rect(fill = "lightblue"),
        panel.background = element_rect(fill = "lightblue"),
        panel.grid = element_line(color = "white"),
        legend.position = "right",
        legend.title = element_text(colour="black", size=8, 
                                      face="bold"),
        legend.text = element_text(angle = 45, hjust = 1, color = "black"),
        legend.background = element_rect(fill = "lightblue"),
        plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "lines"),
        plot.title = element_text(size = 18, hjust=1.3, vjust = -3.0, color = "black"),
        panel.spacing = unit(4, "lines")) +
          
  ggtitle("1985") +
  
  coord_polar()



#chignik, yukon, kushokwim, nroton sound 
```


## Geospatial of Alaska fishing 
```{r}
library(usmap) 


alaska_map <- plot_usmap(include = c("AK")) +
      labs(title = "Western States") 

alaska_map

class(alaska_map)


#alaska_2 <- sf::st_transform(alaska, 3857)


# Without any fillings:

```

Alaska Peninsula/Aleutian Islands
4308937
21544684
195
2
Alaska Peninsula/Aleutian Islands
8197292
40986459
195
3
Chignik
675608
3378039
140
4
Cook Inlet
986653
4933266
195
5
Kodiak
5681055
28405273
195
6
Prince William Sound
13268911
66344554
195
7
Southeast/Yakutat

```{r}

#ggplot(alaska) + geom_sf() + geom_sf(data = geo, shape = 4, col = "red", size = 5)
```




```{r}
regions <- data.frame(
      lon = c(-173.5, -160.6391, -158.4045, -152.644, -152.407, -147.0971, -139.73),
      lat = c(52.09, 57.99, 56.295, 59.37, 57.79, 60.6905, 59.547),
      area = c("Alaska Peninsula/Aleutian Islands", "Bristol Bay", "Chignik", "Cook Inlet", "Kodiak", "Prince William Sound", "Southeast/Yakutat")
)
    # Transform data
    #transformed_data <- usmap_transform(regions)
    # Plot transformed data on map

    
geo <- merge(summary_all, regions)

geo <- geo |> 
  st_as_sf(coords = c("lon", "lat"), crs = "EPSG:4269")


```

```{r}
#state_shape <- st_read("/Users/katebecker/Documents/Bren/Winter/240/HW/eds240-hw2-kateebeckerr/data/Shape/GU_StateOrTerritory.shp")

#crs(state_shape)

```


```{r}

# install.packages("devtools")
#devtools::install_github("UrbanInstitute/urbnmapr")


#states_sf <- get_urbn_map("states", sf = TRUE)

#crs(states_sf)
#states_df <- st_as_sf(states_sf)
#sf::st_crs(states_df) = 4326


#alaska <- states_sf %>%
  #filter(state_name == "Alaska") %>%
  #ggplot() +
    #coord_sf(datum = NA)
```

```{r}

library(sf)
library(dplyr)
library(ggplot2)
library(leaflet)
library(scales)
library(ggmap)

ak_regions <- st_read("data/shapefile_demo_data/ak_regions_simp.shp")

crs(ak_regions)

ak_regions_3338 <- ak_regions %>%
  st_transform(crs = 3338)

geo_3338 <- geo %>%
  st_transform(crs = 3338)

```


```{r}

#ggplot() +
  #geom_sf(data = ak_regions_3338, aes(fill = region)) +
  #geom_sf(data = geo, color = "yellow") +
  #theme(axis.text.x=element_blank(),
        #axis.text.y=element_blank(),
        #axis.ticks=element_blank(),
        #panel.background = element_rect(fill = "lightblue"),
        #panel.border = element_blank(), 
        #panel.grid.major = element_blank(),
        #legend.position = "bottom",
        #legend.title = element_text(colour="black", size=8, 
                                      #face="bold"),
        #legend.text = element_text(family = "josefin",
                               #size = 8))



# scale_fill_gradientn(colours = "#6a5f43", "#997723", "#e8a707", "#b88d22", "#7b5f19", "#b89b50", "#e6d6ab", "#c5bca2", "#a27903", "#4a4023", "#d9d0b6", "#2f2302", "#f7f8c8") + #13
```

```{r}
my_colors <- c("Aleutian Islands" = "#bf0452",
               "Chignik" = "#e8a9ca",
               "Bristol Bay" = "#FF7F50",
               "Kodiak" = "#FF7799",
               "Cook Inlet" = "#ef586d",
               "Prince William Sound" = "#f5237b",
               "Southeast" = "#FF91A4",
               "Norton Sound" = "#b7138c",
               "Arctic" = "#ee6088",
               "Bristol Bay" = "#FD7C6E",
               "Copper River" = "#d35b8d",
               "Yukon" = "#f697dd"
               # Add more regions and corresponding colors as needed
               )


alaska_regions <- ggplot() +
  geom_sf(data = ak_regions_3338, aes(fill = region, alpha = 0.4))+
  scale_fill_manual(values = my_colors) +
  theme(axis.title.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.x = element_text(), 
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_rect(fill = "lightblue"),
        panel.grid.major = element_blank(),
        legend.position = "bottom",
        legend.title = element_text(colour="black", size=12),
        legend.text = element_text(family = "josefin",
                               size = 8)) +
  guides(fill = guide_legend(override.aes = list(alpha = 0)))  
  
  
final_alaska <- alaska_regions +
  geom_sf(data = geo_3338, color = "yellow", shape = 8, size = 2) +
    geom_sf_text(
    data = geo,
    aes(label = area, hjust = -0.08, vjust = 1.5),
    check_overlap = TRUE,
    size = 3,
    color = "black",
    fontface = "bold") +
  geom_label_repel() +
  theme(legend.position = "none") 


final_alaska
```


#Lines

```{r}
cleaned_alaska <- na.omit(alaska)

# Calculate averages
averaged_alaska <- cleaned_alaska %>%
  group_by(year, species_name) %>%
  summarize(avg_number_of_fish = mean(number_of_fish_estimated))

# View the resulting dataframe
print(averaged_alaska)
```


```{r}

averaged_alaska %>%
  ggplot( aes(x=year, y= avg_number_of_fish, group=species_name, color=species_name)) +
    geom_line(linewidth = 2, alpha = 0.8) +
  scale_y_continuous(labels = scales::comma, limits = c(0,30000000), breaks = seq(0, 30000000, by = 5000000), expand =c(0,0)) +
  scale_x_continuous(breaks = unique(averaged_alaska$year), expand = c(0,0)) +
  ggtitle("Salmonoid Catch Distribution Over the Years") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "lightblue"),
        plot.background = element_rect(fill = "lightblue"),
        legend.background = element_rect(fill = "lightblue"),
        plot.title = element_text(hjust = 0.5)
        ) +
  guides(color = guide_legend(title = "Species", override.aes = list(size = 4))) +
  labs(y = "Average Catch Per Year") + 
  scale_color_manual(values = c("#FF7F50", "#f5237b","#bf0452", "#f5237b","#FD7C6E"))
```







